{"pr_number": 770, "pr_title": "Categorize auth errors", "pr_author": "changxu0306", "pr_createdAt": "2020-08-28T06:50:44Z", "pr_url": "https://github.com/aws-amplify/amplify-android/pull/770", "timeline": [{"oid": "40b05168ab2e092cdaf2765ff4c7019d664e2cf5", "url": "https://github.com/aws-amplify/amplify-android/commit/40b05168ab2e092cdaf2765ff4c7019d664e2cf5", "message": "categorize sign up and sign in errors", "committedDate": "2020-08-25T22:11:09Z", "type": "commit"}, {"oid": "5bcad2d8600ed074d181379e8f9151e5bb67d0fe", "url": "https://github.com/aws-amplify/amplify-android/commit/5bcad2d8600ed074d181379e8f9151e5bb67d0fe", "message": "Centralized error mapping and refactored recovery messages", "committedDate": "2020-08-28T06:27:38Z", "type": "commit"}, {"oid": "f7adf48321a1f55608892566e625dc4093ce548f", "url": "https://github.com/aws-amplify/amplify-android/commit/f7adf48321a1f55608892566e625dc4093ce548f", "message": "Delete unnecessary comments", "committedDate": "2020-08-28T06:45:37Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MDU3NTI2Ng==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r480575266", "body": "You could further simplify your code in the plugin, by providing a default exception, here:\r\n```suggestion\r\n        return new AuthException(fallbackMessage, error, \"See attached exception for more details.\");\r\n```\r\nThen, you'd only need to pass in an additional `fallbackMessage` when you call the lookup:\r\n```java\r\nAuthException mapped =\r\n    CognitoAuthExceptionConverter.lookup(\"Fallback message for some situation, here.\", error);\r\n```\r\n\r\nNote: this is just a suggestion. You can choose not to do this.", "bodyText": "You could further simplify your code in the plugin, by providing a default exception, here:\n  \n    \n      \n        Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                    return null;\n          \n          \n            \n                    return new AuthException(fallbackMessage, error, \"See attached exception for more details.\");\n          \n      \n    \n    \n  \n\nThen, you'd only need to pass in an additional fallbackMessage when you call the lookup:\nAuthException mapped =\n    CognitoAuthExceptionConverter.lookup(\"Fallback message for some situation, here.\", error);\nNote: this is just a suggestion. You can choose not to do this.", "bodyHTML": "<p dir=\"auto\">You could further simplify your code in the plugin, by providing a default exception, here:</p>\n  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">        <span class=\"pl-k\">return</span> <span class=\"pl-c1 x x-first x-last\">null</span>;</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">        <span class=\"pl-k\">return</span> <span class=\"pl-k x x-first\">new</span><span class=\"x\"> </span><span class=\"pl-smi x\">AuthException</span><span class=\"x\">(fallbackMessage, error, </span><span class=\"pl-s\"><span class=\"pl-pds x\">\"</span><span class=\"x\">See attached exception for more details.</span><span class=\"pl-pds x\">\"</span></span><span class=\"x x-last\">)</span>;</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n\n<p dir=\"auto\">Then, you'd only need to pass in an additional <code>fallbackMessage</code> when you call the lookup:</p>\n<div class=\"highlight highlight-source-java position-relative overflow-auto\" data-snippet-clipboard-copy-content=\"AuthException mapped =\n    CognitoAuthExceptionConverter.lookup(&quot;Fallback message for some situation, here.&quot;, error);\"><pre><span class=\"pl-smi\">AuthException</span> mapped <span class=\"pl-k\">=</span>\n    <span class=\"pl-smi\">CognitoAuthExceptionConverter</span><span class=\"pl-k\">.</span>lookup(<span class=\"pl-s\"><span class=\"pl-pds\">\"</span>Fallback message for some situation, here.<span class=\"pl-pds\">\"</span></span>, error);</pre></div>\n<p dir=\"auto\">Note: this is just a suggestion. You can choose not to do this.</p>", "author": "jamesonwilliams", "createdAt": "2020-09-01T01:49:42Z", "path": "aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java", "diffHunk": "@@ -0,0 +1,109 @@\n+/*\n+ * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n+ *\n+ * Licensed under the Apache License, Version 2.0 (the \"License\").\n+ * You may not use this file except in compliance with the License.\n+ * A copy of the License is located at\n+ *\n+ *  http://aws.amazon.com/apache2.0\n+ *\n+ * or in the \"license\" file accompanying this file. This file is distributed\n+ * on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n+ * express or implied. See the License for the specific language governing\n+ * permissions and limitations under the License.\n+ */\n+\n+package com.amplifyframework.auth.cognito.util;\n+\n+import com.amplifyframework.auth.AuthException;\n+\n+import com.amazonaws.services.cognitoidentityprovider.model.AliasExistsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeDeliveryFailureException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeMismatchException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ExpiredCodeException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidPasswordException;\n+import com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException;\n+import com.amazonaws.services.cognitoidentityprovider.model.PasswordResetRequiredException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.TooManyFailedAttemptsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UnexpectedLambdaException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotConfirmedException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UsernameExistsException;\n+\n+/**\n+ * Convert AWS Cognito Exceptions to AuthExceptions.\n+ */\n+public final class CognitoAuthExceptionConverter {\n+\n+    /**\n+     * Dis-allows instantiation of this class.\n+     */\n+    private CognitoAuthExceptionConverter() {}\n+\n+    /**\n+     * Lookup method to convert AWS Cognito Exception to AuthException.\n+     * @param error Exception thrown by AWSMobileClient\n+     * @return AuthException\n+     */\n+    public static AuthException lookup(Exception error) {\n+        if (error instanceof UserNotFoundException) {\n+            return new AuthException.UserNotFoundException(error);\n+        }\n+\n+        if (error instanceof UserNotConfirmedException) {\n+            return new AuthException.UserNotConfirmedException(error);\n+        }\n+\n+        if (error instanceof UsernameExistsException) {\n+            return new AuthException.UsernameExistsException(error);\n+        }\n+\n+        if (error instanceof AliasExistsException) {\n+            return new AuthException.AliasExistsException(error);\n+        }\n+\n+        if (error instanceof InvalidPasswordException) {\n+            return new AuthException.InvalidPasswordException(error);\n+        }\n+\n+        if (error instanceof InvalidParameterException) {\n+            return new AuthException.InvalidParameterException(error);\n+        }\n+\n+        if (error instanceof ExpiredCodeException) {\n+            return new AuthException.CodeExpiredException(error);\n+        }\n+\n+        if (error instanceof CodeMismatchException) {\n+            return new AuthException.CodeMismatchException(error);\n+        }\n+\n+        if (error instanceof CodeDeliveryFailureException) {\n+            return new AuthException.CodeDeliveryFailureException(error);\n+        }\n+\n+        if (error instanceof LimitExceededException) {\n+            return new AuthException.LimitExceededException(error);\n+        }\n+\n+        if (error instanceof ResourceNotFoundException) {\n+            return new AuthException.ResourceNotFoundException(error);\n+        }\n+\n+        if (error instanceof TooManyFailedAttemptsException) {\n+            return new AuthException.FailedAttemptsLimitExceededException(error);\n+        }\n+\n+        if (error instanceof UnexpectedLambdaException) {\n+            return new AuthException.LambdaException(error);\n+        }\n+\n+        if (error instanceof PasswordResetRequiredException) {\n+            return new AuthException.PasswordResetRequiredException(error);\n+        }\n+\n+        return null;", "originalCommit": "f7adf48321a1f55608892566e625dc4093ce548f", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTI3MzQ1Nw==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481273457", "bodyText": "This is a very good suggestion!", "author": "changxu0306", "createdAt": "2020-09-01T16:21:35Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MDU3NTI2Ng=="}], "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MDU3NTg3MA==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r480575870", "body": "```suggestion\r\n     * Could not perform the action because Amplify cannot find the requested resource.\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                 * Could not perform the action because Amazon Cognito service cannot find the requested resource.\n          \n          \n            \n                 * Could not perform the action because Amplify cannot find the requested resource.", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because <span class=\"pl-smi x x-first\">Amazon</span><span class=\"x\"> </span><span class=\"pl-smi x\">Cognito</span><span class=\"x x-last\"> service</span> cannot find the requested resource.</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because <span class=\"pl-smi x x-first x-last\">Amplify</span> cannot find the requested resource.</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "jamesonwilliams", "createdAt": "2020-09-01T01:50:17Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,286 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.\n+     */\n+    public static class CodeDeliveryFailureException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Error in delivering the confirmation code.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and send another confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeDeliveryFailureException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user enters incorrect confirmation code.\n+     */\n+    public static class CodeMismatchException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code entered is not correct.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeMismatchException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because confirmation code has expired.\n+     */\n+    public static class CodeExpiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code has expired.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Resend a new confirmation code and then retry operation with it.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeExpiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because there exists incorrect parameters.\n+     */\n+    public static class InvalidParameterException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"One or more parameters are incorrect.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct parameters.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidParameterException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because the password given is invalid.\n+     */\n+    public static class InvalidPasswordException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"The password given is invalid.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct password.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidPasswordException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because number of allowed operation has exceeded.\n+     */\n+    public static class LimitExceededException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Number of allowed operation has exceeded.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Please wait a while before re-attempting or increase the service limit.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public LimitExceededException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because password needs to be reset.\n+     */\n+    public static class PasswordResetRequiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Required to reset the password of the user.\";\n+        private static final String RECOVERY_SUGGESTION = \"Reset the password of the user.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public PasswordResetRequiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because Amazon Cognito service cannot find the requested resource.", "originalCommit": "f7adf48321a1f55608892566e625dc4093ce548f", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MDU3NzI1Nw==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r480577257", "body": "This type of exception is also implementation specific. (The Auth _category_ doesn't need to involved AWS Lambda, necessarily.) I'd recommend to remove this `LambdaException` entirely.", "bodyText": "This type of exception is also implementation specific. (The Auth category doesn't need to involved AWS Lambda, necessarily.) I'd recommend to remove this LambdaException entirely.", "bodyHTML": "<p dir=\"auto\">This type of exception is also implementation specific. (The Auth <em>category</em> doesn't need to involved AWS Lambda, necessarily.) I'd recommend to remove this <code>LambdaException</code> entirely.</p>", "author": "jamesonwilliams", "createdAt": "2020-09-01T01:51:34Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,286 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.\n+     */\n+    public static class CodeDeliveryFailureException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Error in delivering the confirmation code.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and send another confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeDeliveryFailureException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user enters incorrect confirmation code.\n+     */\n+    public static class CodeMismatchException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code entered is not correct.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeMismatchException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because confirmation code has expired.\n+     */\n+    public static class CodeExpiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code has expired.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Resend a new confirmation code and then retry operation with it.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeExpiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because there exists incorrect parameters.\n+     */\n+    public static class InvalidParameterException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"One or more parameters are incorrect.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct parameters.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidParameterException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because the password given is invalid.\n+     */\n+    public static class InvalidPasswordException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"The password given is invalid.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct password.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidPasswordException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because number of allowed operation has exceeded.\n+     */\n+    public static class LimitExceededException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Number of allowed operation has exceeded.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Please wait a while before re-attempting or increase the service limit.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public LimitExceededException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because password needs to be reset.\n+     */\n+    public static class PasswordResetRequiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Required to reset the password of the user.\";\n+        private static final String RECOVERY_SUGGESTION = \"Reset the password of the user.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public PasswordResetRequiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because Amazon Cognito service cannot find the requested resource.\n+     */\n+    public static class ResourceNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Could not find the requested online resource.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry with exponential back-off\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public ResourceNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user made too many failed attempts for a given action.\n+     */\n+    public static class FailedAttemptsLimitExceededException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User has made too many failed attempts for a given action.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Please check out the service configuration to see the condition of locking.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public FailedAttemptsLimitExceededException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because Amazon Cognito service encounters an invalid AWS Lambda response\n+     * or encounters an unexpected exception with the AWS Lambda service.\n+     */\n+    public static class LambdaException extends AuthException {", "originalCommit": "f7adf48321a1f55608892566e625dc4093ce548f", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MDU3Nzc3MQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r480577771", "body": "Mentions two details of the implementation -- Cognito, Lambda. That's fine for the _plugin_, but not the category, which is abstract.", "bodyText": "Mentions two details of the implementation -- Cognito, Lambda. That's fine for the plugin, but not the category, which is abstract.", "bodyHTML": "<p dir=\"auto\">Mentions two details of the implementation -- Cognito, Lambda. That's fine for the <em>plugin</em>, but not the category, which is abstract.</p>", "author": "jamesonwilliams", "createdAt": "2020-09-01T01:52:05Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,286 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.\n+     */\n+    public static class CodeDeliveryFailureException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Error in delivering the confirmation code.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and send another confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeDeliveryFailureException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user enters incorrect confirmation code.\n+     */\n+    public static class CodeMismatchException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code entered is not correct.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeMismatchException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because confirmation code has expired.\n+     */\n+    public static class CodeExpiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code has expired.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Resend a new confirmation code and then retry operation with it.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeExpiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because there exists incorrect parameters.\n+     */\n+    public static class InvalidParameterException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"One or more parameters are incorrect.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct parameters.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidParameterException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because the password given is invalid.\n+     */\n+    public static class InvalidPasswordException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"The password given is invalid.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct password.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidPasswordException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because number of allowed operation has exceeded.\n+     */\n+    public static class LimitExceededException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Number of allowed operation has exceeded.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Please wait a while before re-attempting or increase the service limit.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public LimitExceededException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because password needs to be reset.\n+     */\n+    public static class PasswordResetRequiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Required to reset the password of the user.\";\n+        private static final String RECOVERY_SUGGESTION = \"Reset the password of the user.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public PasswordResetRequiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because Amazon Cognito service cannot find the requested resource.\n+     */\n+    public static class ResourceNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Could not find the requested online resource.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry with exponential back-off\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public ResourceNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user made too many failed attempts for a given action.\n+     */\n+    public static class FailedAttemptsLimitExceededException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User has made too many failed attempts for a given action.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Please check out the service configuration to see the condition of locking.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public FailedAttemptsLimitExceededException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because Amazon Cognito service encounters an invalid AWS Lambda response", "originalCommit": "f7adf48321a1f55608892566e625dc4093ce548f", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"oid": "3498ed6404da66e8ce9b71068da4e6c27808c990", "url": "https://github.com/aws-amplify/amplify-android/commit/3498ed6404da66e8ce9b71068da4e6c27808c990", "message": "remove unused classes, ge rid of plugin specific info in core", "committedDate": "2020-09-01T17:21:19Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTMyMDIxNQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481320215", "body": "A bit of nit picking but it was counter intuitive to me seeing this used with the string as the first parameter. It makes it seem like the string is what you're looking up. I think it'd be more intuitive to change the order of these parameters to make clear you're looking up the error and then specifying what message to use. You can use Android Studio to easily refactor the parameter order without having to worry about changing all the places this is used manually.", "bodyText": "A bit of nit picking but it was counter intuitive to me seeing this used with the string as the first parameter. It makes it seem like the string is what you're looking up. I think it'd be more intuitive to change the order of these parameters to make clear you're looking up the error and then specifying what message to use. You can use Android Studio to easily refactor the parameter order without having to worry about changing all the places this is used manually.", "bodyHTML": "<p dir=\"auto\">A bit of nit picking but it was counter intuitive to me seeing this used with the string as the first parameter. It makes it seem like the string is what you're looking up. I think it'd be more intuitive to change the order of these parameters to make clear you're looking up the error and then specifying what message to use. You can use Android Studio to easily refactor the parameter order without having to worry about changing all the places this is used manually.</p>", "author": "TrekSoft", "createdAt": "2020-09-01T17:41:20Z", "path": "aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java", "diffHunk": "@@ -0,0 +1,106 @@\n+/*\n+ * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n+ *\n+ * Licensed under the Apache License, Version 2.0 (the \"License\").\n+ * You may not use this file except in compliance with the License.\n+ * A copy of the License is located at\n+ *\n+ *  http://aws.amazon.com/apache2.0\n+ *\n+ * or in the \"license\" file accompanying this file. This file is distributed\n+ * on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n+ * express or implied. See the License for the specific language governing\n+ * permissions and limitations under the License.\n+ */\n+\n+package com.amplifyframework.auth.cognito.util;\n+\n+import com.amplifyframework.auth.AuthException;\n+\n+import com.amazonaws.services.cognitoidentityprovider.model.AliasExistsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeDeliveryFailureException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeMismatchException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ExpiredCodeException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidPasswordException;\n+import com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException;\n+import com.amazonaws.services.cognitoidentityprovider.model.PasswordResetRequiredException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.TooManyFailedAttemptsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotConfirmedException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UsernameExistsException;\n+\n+/**\n+ * Convert AWS Cognito Exceptions to AuthExceptions.\n+ */\n+public final class CognitoAuthExceptionConverter {\n+\n+    /**\n+     * Dis-allows instantiation of this class.\n+     */\n+    private CognitoAuthExceptionConverter() {}\n+\n+    /**\n+     * Lookup method to convert AWS Cognito Exception to AuthException.\n+     * @param fallbackMessage Fallback message to inform failure\n+     * @param error Exception thrown by AWSMobileClient\n+     * @return AuthException\n+     */\n+    public static AuthException lookup(String fallbackMessage, Exception error) {", "originalCommit": "3498ed6404da66e8ce9b71068da4e6c27808c990", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTMzMDMyNQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481330325", "bodyText": "I really like this detailed suggestion\ud83d\ude04 Yeah it's just like reading a book and the order of parameters matters a lot.", "author": "changxu0306", "createdAt": "2020-09-01T17:58:53Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTMyMDIxNQ=="}], "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTMyMjE5Ng==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481322196", "body": "\"... or check your config file to be sure the endpoint is valid.\"", "bodyText": "\"... or check your config file to be sure the endpoint is valid.\"", "bodyHTML": "<p dir=\"auto\">\"... or check your config file to be sure the endpoint is valid.\"</p>", "author": "TrekSoft", "createdAt": "2020-09-01T17:44:50Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,230 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.\n+     */\n+    public static class CodeDeliveryFailureException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Error in delivering the confirmation code.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and send another confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeDeliveryFailureException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user enters incorrect confirmation code.\n+     */\n+    public static class CodeMismatchException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code entered is not correct.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeMismatchException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because confirmation code has expired.\n+     */\n+    public static class CodeExpiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code has expired.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Resend a new confirmation code and then retry operation with it.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeExpiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because there exists incorrect parameters.\n+     */\n+    public static class InvalidParameterException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"One or more parameters are incorrect.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct parameters.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidParameterException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because the password given is invalid.\n+     */\n+    public static class InvalidPasswordException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"The password given is invalid.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct password.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public InvalidPasswordException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because number of allowed operation has exceeded.\n+     */\n+    public static class LimitExceededException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Number of allowed operation has exceeded.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Please wait a while before re-attempting or increase the service limit.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public LimitExceededException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because password needs to be reset.\n+     */\n+    public static class PasswordResetRequiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Required to reset the password of the user.\";\n+        private static final String RECOVERY_SUGGESTION = \"Reset the password of the user.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public PasswordResetRequiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because Amplify cannot find the requested resource.\n+     */\n+    public static class ResourceNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Could not find the requested online resource.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry with exponential back-off\";", "originalCommit": "3498ed6404da66e8ce9b71068da4e6c27808c990", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"oid": "d38fcc4f6f694183f24553dda5253c956ff28e92", "url": "https://github.com/aws-amplify/amplify-android/commit/d38fcc4f6f694183f24553dda5253c956ff28e92", "message": "Refactor recovery message", "committedDate": "2020-09-01T18:13:26Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0MTIwOA==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481341208", "body": "quick description? e.g.\r\n```\r\n@return AuthException Specific exception for Amplify Auth\r\n```", "bodyText": "quick description? e.g.\n@return AuthException Specific exception for Amplify Auth", "bodyHTML": "<p dir=\"auto\">quick description? e.g.</p>\n<div class=\"snippet-clipboard-content position-relative overflow-auto\" data-snippet-clipboard-copy-content=\"@return AuthException Specific exception for Amplify Auth\"><pre><code>@return AuthException Specific exception for Amplify Auth\n</code></pre></div>", "author": "raphkim", "createdAt": "2020-09-01T18:18:53Z", "path": "aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java", "diffHunk": "@@ -0,0 +1,106 @@\n+/*\n+ * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n+ *\n+ * Licensed under the Apache License, Version 2.0 (the \"License\").\n+ * You may not use this file except in compliance with the License.\n+ * A copy of the License is located at\n+ *\n+ *  http://aws.amazon.com/apache2.0\n+ *\n+ * or in the \"license\" file accompanying this file. This file is distributed\n+ * on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n+ * express or implied. See the License for the specific language governing\n+ * permissions and limitations under the License.\n+ */\n+\n+package com.amplifyframework.auth.cognito.util;\n+\n+import com.amplifyframework.auth.AuthException;\n+\n+import com.amazonaws.services.cognitoidentityprovider.model.AliasExistsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeDeliveryFailureException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeMismatchException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ExpiredCodeException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidPasswordException;\n+import com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException;\n+import com.amazonaws.services.cognitoidentityprovider.model.PasswordResetRequiredException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.TooManyFailedAttemptsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotConfirmedException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UsernameExistsException;\n+\n+/**\n+ * Convert AWS Cognito Exceptions to AuthExceptions.\n+ */\n+public final class CognitoAuthExceptionConverter {\n+\n+    /**\n+     * Dis-allows instantiation of this class.\n+     */\n+    private CognitoAuthExceptionConverter() {}\n+\n+    /**\n+     * Lookup method to convert AWS Cognito Exception to AuthException.\n+     * @param error Exception thrown by AWSMobileClient\n+     * @param fallbackMessage Fallback message to inform failure\n+     * @return AuthException", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0MjQ3Ng==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481342476", "body": "```suggestion\r\n     * Could not perform the action because user entered incorrect confirmation code.\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                 * Could not perform the action because user enters incorrect confirmation code.\n          \n          \n            \n                 * Could not perform the action because user entered incorrect confirmation code.", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because user <span class=\"x x-first x-last\">enters</span> incorrect confirmation code.</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because user <span class=\"x x-first x-last\">entered</span> incorrect confirmation code.</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "raphkim", "createdAt": "2020-09-01T18:21:07Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,231 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.\n+     */\n+    public static class CodeDeliveryFailureException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Error in delivering the confirmation code.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and send another confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeDeliveryFailureException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user enters incorrect confirmation code.", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0MjY3MQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481342671", "body": "```suggestion\r\n     * Could not perform the action because error occurred when delivering the confirmation code.\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                 * Could not perform the action because error occurs when delivering the confirmation code.\n          \n          \n            \n                 * Could not perform the action because error occurred when delivering the confirmation code.", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because error <span class=\"x x-first x-last\">occurs</span> when delivering the confirmation code.</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because error <span class=\"x x-first x-last\">occurred</span> when delivering the confirmation code.</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "raphkim", "createdAt": "2020-09-01T18:21:29Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,231 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0Mjg1MQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481342851", "body": "```suggestion\r\n     * Could not perform the action because user is not confirmed in the system.\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                 * Could not perform the action because user not confirmed in the system.\n          \n          \n            \n                 * Could not perform the action because user is not confirmed in the system.", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because user not confirmed in the system.</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because user <span class=\"x x-first x-last\">is </span>not confirmed in the system.</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "raphkim", "createdAt": "2020-09-01T18:21:49Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,231 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0Mjk1OQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481342959", "body": "```suggestion\r\n     * Could not perform the action because user was not found in the system.\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                 * Could not perform the action because user not found in the system.\n          \n          \n            \n                 * Could not perform the action because user was not found in the system.", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because user not found in the system.</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because user <span class=\"x x-first x-last\">was </span>not found in the system.</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "raphkim", "createdAt": "2020-09-01T18:21:59Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,231 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0MzM0Ng==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481343346", "body": "```suggestion\r\n     * Could not perform the action because there are incorrect parameters.\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                 * Could not perform the action because there exists incorrect parameters.\n          \n          \n            \n                 * Could not perform the action because there are incorrect parameters.", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because there <span class=\"x x-first x-last\">exists</span> incorrect parameters.</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">     <span class=\"pl-k\">*</span> <span class=\"pl-smi\">Could</span> not perform the action because there <span class=\"x x-first x-last\">are</span> incorrect parameters.</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "raphkim", "createdAt": "2020-09-01T18:22:45Z", "path": "core/src/main/java/com/amplifyframework/auth/AuthException.java", "diffHunk": "@@ -191,4 +191,231 @@ public UnknownException(Throwable cause) {\n             );\n         }\n     }\n+\n+    /**\n+     * Could not perform the action because user not found in the system.\n+     */\n+    public static class UserNotFoundException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not found in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please enter correct username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         *\n+         * @param cause The original error.\n+         */\n+        public UserNotFoundException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user not confirmed in the system.\n+     */\n+    public static class UserNotConfirmedException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"User not confirmed in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Please confirm user first and then retry operation\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UserNotConfirmedException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because username already exists in the system.\n+     */\n+    public static class UsernameExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Username already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and enter another username.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public UsernameExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because alias (an account with certain email or phone) already exists in the system.\n+     */\n+    public static class AliasExistsException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE =\n+                \"Alias (an account with this email or phone) already exists in the system.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and use another alias.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public AliasExistsException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because error occurs when delivering the confirmation code.\n+     */\n+    public static class CodeDeliveryFailureException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Error in delivering the confirmation code.\";\n+        private static final String RECOVERY_SUGGESTION = \"Retry operation and send another confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeDeliveryFailureException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because user enters incorrect confirmation code.\n+     */\n+    public static class CodeMismatchException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code entered is not correct.\";\n+        private static final String RECOVERY_SUGGESTION = \"Enter correct confirmation code.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeMismatchException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because confirmation code has expired.\n+     */\n+    public static class CodeExpiredException extends AuthException {\n+        private static final long serialVersionUID = 1L;\n+        private static final String MESSAGE = \"Confirmation code has expired.\";\n+        private static final String RECOVERY_SUGGESTION =\n+                \"Resend a new confirmation code and then retry operation with it.\";\n+\n+        /**\n+         * Default message/recovery suggestion with a cause.\n+         * @param cause The original error.\n+         */\n+        public CodeExpiredException(Throwable cause) {\n+            super(MESSAGE, cause, RECOVERY_SUGGESTION);\n+        }\n+    }\n+\n+    /**\n+     * Could not perform the action because there exists incorrect parameters.", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0NDg3MA==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481344870", "body": "Prefix with `@NonNull` to let developers know that this operation always returns a non-null exception.\r\nThe parameters should also have `@NonNull` and/or `@Nullable` tags.\r\n\r\nThe above practice should be used for every publicly exposed methods throughout the repo :)", "bodyText": "Prefix with @NonNull to let developers know that this operation always returns a non-null exception.\nThe parameters should also have @NonNull and/or @Nullable tags.\nThe above practice should be used for every publicly exposed methods throughout the repo :)", "bodyHTML": "<p dir=\"auto\">Prefix with <code>@NonNull</code> to let developers know that this operation always returns a non-null exception.<br>\nThe parameters should also have <code>@NonNull</code> and/or <code>@Nullable</code> tags.</p>\n<p dir=\"auto\">The above practice should be used for every publicly exposed methods throughout the repo :)</p>", "author": "raphkim", "createdAt": "2020-09-01T18:25:35Z", "path": "aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java", "diffHunk": "@@ -0,0 +1,106 @@\n+/*\n+ * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n+ *\n+ * Licensed under the Apache License, Version 2.0 (the \"License\").\n+ * You may not use this file except in compliance with the License.\n+ * A copy of the License is located at\n+ *\n+ *  http://aws.amazon.com/apache2.0\n+ *\n+ * or in the \"license\" file accompanying this file. This file is distributed\n+ * on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n+ * express or implied. See the License for the specific language governing\n+ * permissions and limitations under the License.\n+ */\n+\n+package com.amplifyframework.auth.cognito.util;\n+\n+import com.amplifyframework.auth.AuthException;\n+\n+import com.amazonaws.services.cognitoidentityprovider.model.AliasExistsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeDeliveryFailureException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeMismatchException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ExpiredCodeException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidPasswordException;\n+import com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException;\n+import com.amazonaws.services.cognitoidentityprovider.model.PasswordResetRequiredException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.TooManyFailedAttemptsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotConfirmedException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UsernameExistsException;\n+\n+/**\n+ * Convert AWS Cognito Exceptions to AuthExceptions.\n+ */\n+public final class CognitoAuthExceptionConverter {\n+\n+    /**\n+     * Dis-allows instantiation of this class.\n+     */\n+    private CognitoAuthExceptionConverter() {}\n+\n+    /**\n+     * Lookup method to convert AWS Cognito Exception to AuthException.\n+     * @param error Exception thrown by AWSMobileClient\n+     * @param fallbackMessage Fallback message to inform failure\n+     * @return AuthException\n+     */\n+    public static AuthException lookup(Exception error, String fallbackMessage) {", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ4MTM0NTE1OA==", "url": "https://github.com/aws-amplify/amplify-android/pull/770#discussion_r481345158", "body": "```suggestion\r\n    @NonNull\r\n    public static AuthException lookup(@NonNull Exception error, @NonNull String fallbackMessage) {\r\n```", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                public static AuthException lookup(Exception error, String fallbackMessage) {\n          \n          \n            \n                @NonNull\n          \n          \n            \n                public static AuthException lookup(@NonNull Exception error, @NonNull String fallbackMessage) {", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">    <span class=\"pl-k x x-first\">public</span><span class=\"x\"> </span><span class=\"pl-k x\">static</span><span class=\"x\"> </span><span class=\"pl-smi x\">AuthException</span><span class=\"x\"> lookup(</span><span class=\"pl-smi x\">Exception</span><span class=\"x\"> error, </span><span class=\"pl-smi x\">String</span><span class=\"x x-last\"> fallbackMessage) {</span></td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">    <span class=\"pl-k x x-first x-last\">@NonNull</span></td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">    <span class=\"pl-k\">public</span> <span class=\"pl-k\">static</span> <span class=\"pl-smi\">AuthException</span> lookup(<span class=\"pl-k\">@NonNull</span> <span class=\"pl-smi\">Exception</span> error, <span class=\"pl-k\">@NonNull</span> <span class=\"pl-smi\">String</span> fallbackMessage) {</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "raphkim", "createdAt": "2020-09-01T18:26:07Z", "path": "aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java", "diffHunk": "@@ -0,0 +1,106 @@\n+/*\n+ * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n+ *\n+ * Licensed under the Apache License, Version 2.0 (the \"License\").\n+ * You may not use this file except in compliance with the License.\n+ * A copy of the License is located at\n+ *\n+ *  http://aws.amazon.com/apache2.0\n+ *\n+ * or in the \"license\" file accompanying this file. This file is distributed\n+ * on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n+ * express or implied. See the License for the specific language governing\n+ * permissions and limitations under the License.\n+ */\n+\n+package com.amplifyframework.auth.cognito.util;\n+\n+import com.amplifyframework.auth.AuthException;\n+\n+import com.amazonaws.services.cognitoidentityprovider.model.AliasExistsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeDeliveryFailureException;\n+import com.amazonaws.services.cognitoidentityprovider.model.CodeMismatchException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ExpiredCodeException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException;\n+import com.amazonaws.services.cognitoidentityprovider.model.InvalidPasswordException;\n+import com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException;\n+import com.amazonaws.services.cognitoidentityprovider.model.PasswordResetRequiredException;\n+import com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.TooManyFailedAttemptsException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotConfirmedException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException;\n+import com.amazonaws.services.cognitoidentityprovider.model.UsernameExistsException;\n+\n+/**\n+ * Convert AWS Cognito Exceptions to AuthExceptions.\n+ */\n+public final class CognitoAuthExceptionConverter {\n+\n+    /**\n+     * Dis-allows instantiation of this class.\n+     */\n+    private CognitoAuthExceptionConverter() {}\n+\n+    /**\n+     * Lookup method to convert AWS Cognito Exception to AuthException.\n+     * @param error Exception thrown by AWSMobileClient\n+     * @param fallbackMessage Fallback message to inform failure\n+     * @return AuthException\n+     */\n+    public static AuthException lookup(Exception error, String fallbackMessage) {", "originalCommit": "d38fcc4f6f694183f24553dda5253c956ff28e92", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"oid": "f0d341559552596a584105b36ffed31641d6cdca", "url": "https://github.com/aws-amplify/amplify-android/commit/f0d341559552596a584105b36ffed31641d6cdca", "message": "Revise comments and set non-null prefix to error lookup method", "committedDate": "2020-09-01T18:40:43Z", "type": "commit"}]}