{"pr_number": 942, "pr_title": "feat(datastore) swallow unauthorized errors for subscriptions", "pr_author": "richardmcclellan", "pr_createdAt": "2020-10-30T05:40:45Z", "pr_url": "https://github.com/aws-amplify/amplify-android/pull/942", "timeline": [{"oid": "c81c904beabc0b2e82c823c40be175b72121ad32", "url": "https://github.com/aws-amplify/amplify-android/commit/c81c904beabc0b2e82c823c40be175b72121ad32", "message": "feat(datastore) subscription processor should not fail due to an Unauthorized error", "committedDate": "2020-10-30T05:35:10Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUxNTI3NjY3OQ==", "url": "https://github.com/aws-amplify/amplify-android/pull/942#discussion_r515276679", "body": "```suggestion\n            return Immutable.of(errors);\n```\n", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                        return errors;\n          \n          \n            \n                        return Immutable.of(errors);", "bodyHTML": "  <div class=\"my-2 border rounded-1 js-suggested-changes-blob diff-view js-check-bidi\" id=\"\">\n    <div class=\"f6 p-2 lh-condensed border-bottom d-flex\">\n      <div class=\"flex-auto flex-items-center color-fg-muted\">\n        Suggested change\n        <span class=\"tooltipped tooltipped-multiline tooltipped-s\" aria-label=\"This code change can be committed by users with write permissions.\">\n          <svg aria-hidden=\"true\" height=\"16\" viewBox=\"0 0 16 16\" version=\"1.1\" width=\"16\" data-view-component=\"true\" class=\"octicon octicon-info hide-sm\">\n    <path fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8zm6.5-.25A.75.75 0 017.25 7h1a.75.75 0 01.75.75v2.75h.25a.75.75 0 010 1.5h-2a.75.75 0 010-1.5h.25v-2h-.25a.75.75 0 01-.75-.75zM8 6a1 1 0 100-2 1 1 0 000 2z\"></path>\n</svg>\n        </span>\n      </div>\n    </div>\n    <div itemprop=\"text\" class=\"blob-wrapper data file\" style=\"margin: 0; border: none; overflow-y: visible; overflow-x: auto;\">\n      <table class=\"d-table tab-size mb-0 width-full\" data-paste-markdown-skip=\"\">\n          <tbody><tr class=\"border-0\">\n            <td class=\"blob-num blob-num-deletion text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-deletion js-blob-code-deletion blob-code-marker-deletion\">            <span class=\"pl-k\">return</span> errors;</td>\n          </tr>\n          <tr class=\"border-0\">\n            <td class=\"blob-num blob-num-addition text-right border-0 px-2 py-1 lh-default\" data-line-number=\"\"></td>\n            <td class=\"border-0 px-2 py-1 blob-code-inner blob-code-addition js-blob-code-addition blob-code-marker-addition\">            <span class=\"pl-k\">return</span> <span class=\"pl-smi x x-first\">Immutable</span><span class=\"pl-k x\">.</span><span class=\"x x-last\">of(</span>errors<span class=\"x x-first x-last\">)</span>;</td>\n          </tr>\n      </tbody></table>\n    </div>\n    <div class=\"js-apply-changes\"></div>\n  </div>\n", "author": "jamesonwilliams", "createdAt": "2020-10-30T17:48:12Z", "path": "core/src/main/java/com/amplifyframework/datastore/DataStoreException.java", "diffHunk": "@@ -51,4 +56,61 @@ public DataStoreException(\n     ) {\n         super(message, recoverySuggestion);\n     }\n+\n+    /**\n+     * Exception thrown by DataStore category plugins used to represent a GraphQLResponse containing errors.\n+     */\n+    public static final class GraphQLResponseException extends DataStoreException {\n+        private static final long serialVersionUID = 1L;\n+\n+        private final List<GraphQLResponse.Error> errors;\n+\n+        /**\n+         * Constructs a new exception using the provided message and list of errors.\n+         * @param message Explains the reason for the exception\n+         * @param errors List of errors from GraphQLResponse\n+         */\n+        public GraphQLResponseException(String message, @NonNull List<GraphQLResponse.Error> errors) {\n+            super(message, \"See attached list of GraphQLResponse.Error objects.\");\n+            this.errors = Objects.requireNonNull(errors);\n+        }\n+\n+        /**\n+         * Returns the errors.\n+         * @return the errors.\n+         */\n+        @NonNull\n+        public List<GraphQLResponse.Error> getErrors() {\n+            return errors;", "originalCommit": "c81c904beabc0b2e82c823c40be175b72121ad32", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUxNTI3ODQ0Mg==", "url": "https://github.com/aws-amplify/amplify-android/pull/942#discussion_r515278442", "body": "If we consume the `InterruptedException` will we leave the thread in an indeterminate state? Will the thread hang?", "bodyText": "If we consume the InterruptedException will we leave the thread in an indeterminate state? Will the thread hang?", "bodyHTML": "<p dir=\"auto\">If we consume the <code>InterruptedException</code> will we leave the thread in an indeterminate state? Will the thread hang?</p>", "author": "jamesonwilliams", "createdAt": "2020-10-30T17:51:11Z", "path": "aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java", "diffHunk": "@@ -317,27 +325,35 @@ private String buildConnectionRequestUrl() throws ApiException {\n             this.responseType = responseType;\n             this.subscriptionReadyAcknowledgment = new CountDownLatch(1);\n             this.subscriptionCompletionAcknowledgement = new CountDownLatch(1);\n+            this.failed = false;\n         }\n \n         void acknowledgeSubscriptionReady() {\n             subscriptionReadyAcknowledgment.countDown();\n         }\n \n+        void acknowledgeSubscriptionFailure() {\n+            failed = true;\n+            subscriptionReadyAcknowledgment.countDown();\n+        }\n+\n         boolean awaitSubscriptionReady() {\n             try {\n                 if (!subscriptionReadyAcknowledgment.await(ACKNOWLEDGEMENT_TIMEOUT, TimeUnit.SECONDS)) {\n                     dispatchError(new ApiException(\n-                        \"Subscription not acknowledged.\",\n+                        \"Timed out waiting for subscription start_ack.\",\n                         AmplifyException.TODO_RECOVERY_SUGGESTION\n                     ));\n                     return false;\n+                } else if (failed) {\n+                    // An error was already dispatched at the time of failure, so don't dispatch a second one.\n+                    return false;\n                 }\n             } catch (InterruptedException interruptedException) {\n-                dispatchError(new ApiException(\n-                    \"Failure awaiting subscription acknowledgement.\",\n-                    interruptedException,\n-                    AmplifyException.TODO_RECOVERY_SUGGESTION\n-                ));\n+                // Triggered when the Future created in SubscriptionOperation is cancelled, which happens when the\n+                // subscription Observable is disposed, which happens when a SUBSCRIPTION_ERROR occurs.  Don't dispatch\n+                // any error because the caller has likely already been disposed.\n+                LOG.warn(\"Thread interrupted awaiting subscription acknowledgement.\", interruptedException);", "originalCommit": "c81c904beabc0b2e82c823c40be175b72121ad32", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUxNTI5ODI2OA==", "url": "https://github.com/aws-amplify/amplify-android/pull/942#discussion_r515298268", "bodyText": "For the scenario where I observed this error happening, no.  The InterruptedException is thrown because cancel was called on the SubscriptionOperation, which then tries to cancel the Future.\nThere may be other scenarios that could cause an InterruptedException, but I think they should probably be handled similarly - stop, do any cleanup that you can, and return immediately.  Dispatching an error to the observer fails because the observer has already been disposed.\nNote though that this particular change is not needed for \"swallowing unauthorized errors for subscriptions\" since the errors are swallowed, and an interruption is prevented.   This change just improves handling of other errors that are not swallowed.", "author": "richardmcclellan", "createdAt": "2020-10-30T18:24:41Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUxNTI3ODQ0Mg=="}], "type": "inlineReview"}, {"oid": "3a5302f3eba1366634af7bd8bf5f6c3c5a5f5dc0", "url": "https://github.com/aws-amplify/amplify-android/commit/3a5302f3eba1366634af7bd8bf5f6c3c5a5f5dc0", "message": "Update core/src/main/java/com/amplifyframework/datastore/DataStoreException.java\n\nCo-authored-by: Jameson Williams <jhwill@amazon.com>", "committedDate": "2020-10-30T18:46:34Z", "type": "commit"}, {"oid": "3a5302f3eba1366634af7bd8bf5f6c3c5a5f5dc0", "url": "https://github.com/aws-amplify/amplify-android/commit/3a5302f3eba1366634af7bd8bf5f6c3c5a5f5dc0", "message": "Update core/src/main/java/com/amplifyframework/datastore/DataStoreException.java\n\nCo-authored-by: Jameson Williams <jhwill@amazon.com>", "committedDate": "2020-10-30T18:46:34Z", "type": "forcePushed"}]}